model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
cache_dir: /scratch/indrisch/huggingface/hub
image_max_pixels: 65536
video_max_pixels: 16384
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
dataset: SQA3Devery24
media_dir: /project/aip-wangcs/shared/data/
template: qwen2_vl
cutoff_len: 131072
max_samples: 100
overwrite_cache: true
preprocessing_num_workers: 32
dataloader_num_workers: 4
low_cpu_mem_usage: true
output_dir: saves/qwen2_5vl-7b/lora/sft/SQA3Devery24_traineval
logging_steps: 1
save_steps: 1
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 252
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: /project/aip-wangcs/indrisch//LLaMA-Factory/saves/qwen2_5vl-7b/lora/sft/SQA3Devery24_traineval/checkpoint-500/
debug: underflow_overflow
log_level: debug
log_level_replica: debug
print_param_status: true
flash_attn: fa2
enable_liger_kernel: true
deepspeed: examples/deepspeed/ds_z3_offload_config.json
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
